[[redirects]]
  from="/*"
  to="/index.html"
  status=200

[build]
  command='pnpm build'
  functions="netlify/functions"
	publish="public"

[functions]
  node_bundler="esbuild"

[build.environment]
  NODE_VERSION="20"